In [1]:
import pandas as pd

C:\Users\lenovo\Anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\lenovo\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.EL2C6PLE4ZYW3ECEVIV3OXXGRN2NRFM2.gfortran-win_amd64.dll
C:\Users\lenovo\Anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"


In [3]:
data = [('MS Dhoni','CSK', 12, 300 ), ('Virat', 'RCB', 12, 350), ('Faf Du plesis', 'RCB',12, 625), ('Surya', 'MI', 12, 575), ('Yashashwi', 'RR',12,600)]

df = pd.DataFrame(data, columns=['Player_Name','IPL_Team','Matches_Played','Runs_Scored'])
df


Player_Name IPL_Team  Matches_Played  Runs_Scored
0       MS Dhoni      CSK              12          300
1          Virat      RCB              12          350
2  Faf Du plesis      RCB              12          625
3          Surya       MI              12          575
4      Yashashwi       RR              12          600

In [14]:
# What is the maximum runs scored by anyone?
# Who has scored the max runs?

df.Player_Name[df['Runs_Scored'] == df.Runs_Scored.max()]

2    Faf Du plesis
Name: Player_Name, dtype: object

In [18]:
player_name = df.loc[df['Runs_Scored'].idxmax(), 'Player_Name']
player_name

'Faf Du plesis'

In [20]:
df['Runs_Scored'].idxmax()

2

In [22]:
df.loc[2, 'Player_Name']

'Faf Du plesis'

In [23]:
df

Player_Name IPL_Team  Matches_Played  Runs_Scored
0       MS Dhoni      CSK              12          300
1          Virat      RCB              12          350
2  Faf Du plesis      RCB              12          625
3          Surya       MI              12          575
4      Yashashwi       RR              12          600

In [34]:
df = df.append({'Player_Name':'Sanju Samson','IPL_Team':'RR', 'Matches_Played':12, 'Runs_Scored':425}, ignore_index=True)

C:\Users\lenovo\AppData\Local\Temp/ipykernel_29776/793136726.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({'Player_Name':'Sanju Samson','IPL_Team':'RR', 'Matches_Played':12, 'Runs_Scored':425}, ignore_index=True)


In [39]:
df

Player_Name IPL_Team  Matches_Played  Runs_Scored
0       MS Dhoni      CSK              12          300
1          Virat      RCB              12          350
2  Faf Du plesis      RCB              12          625
3          Surya       MI              12          575
4      Yashashwi       RR              12          600
5   Sanju Samson       RR              12          425

In [43]:
df.loc[len(df)] = ['Shubman Gill', 'GT', 12, 610]

In [46]:
df

Player_Name IPL_Team  Matches_Played  Runs_Scored
0       MS Dhoni      CSK              12          300
1          Virat      RCB              12          350
2  Faf Du plesis      RCB              12          625
3          Surya       MI              12          575
4      Yashashwi       RR              12          600
5   Sanju Samson       RR              12          425
6   Shubman Gill       GT              12          610

In [47]:
df['Player_Name']

0         MS Dhoni
1            Virat
2    Faf Du plesis
3            Surya
4        Yashashwi
5     Sanju Samson
6     Shubman Gill
Name: Player_Name, dtype: object

In [51]:
df['Player_Name'].tolist()

['MS Dhoni',
 'Virat',
 'Faf Du plesis',
 'Surya',
 'Yashashwi',
 'Sanju Samson',
 'Shubman Gill']

In [52]:
df['Player_Name'].values

array(['MS Dhoni', 'Virat', 'Faf Du plesis', 'Surya', 'Yashashwi',
       'Sanju Samson', 'Shubman Gill'], dtype=object)

In [53]:
df['Player_Name'].values.tolist()

['MS Dhoni',
 'Virat',
 'Faf Du plesis',
 'Surya',
 'Yashashwi',
 'Sanju Samson',
 'Shubman Gill']

In [56]:
df[['Player_Name']]

Player_Name
0       MS Dhoni
1          Virat
2  Faf Du plesis
3          Surya
4      Yashashwi
5   Sanju Samson
6   Shubman Gill

In [57]:
type(df['Player_Name'])

pandas.core.series.Series

In [64]:
df[['Player_Name','IPL_Team']]

Player_Name IPL_Team
0       MS Dhoni      CSK
1          Virat      RCB
2  Faf Du plesis      RCB
3          Surya       MI
4      Yashashwi       RR
5   Sanju Samson       RR
6   Shubman Gill       GT

In [65]:
df.to_csv('players.csv')

In [69]:
df1= pd.read_csv('players.csv',header=None )

In [70]:
df1

0              1    2   3    4
0  0       MS Dhoni  CSK  12  300
1  1          Virat  RCB  12  350
2  2  Faf Du plesis  RCB  12  625
3  3          Surya   MI  12  575
4  4      Yashashwi   RR  12  600
5  5   Sanju Samson   RR  12  425
6  6   Shubman Gill   GT  12  610

In [76]:
df2 = pd.read_csv('players.tsv', sep='\t')
df2

0       MS Dhoni  CSK  12  300
0  1          Virat  RCB  12  350
1  2  Faf Du plesis  RCB  12  625
2  3          Surya   MI  12  575
3  4      Yashashwi   RR  12  600
4  5   Sanju Samson   RR  12  425
5  6   Shubman Gill   GT  12  610

In [77]:
df3 = pd.read_csv('players.tsv')
df3

0\tMS Dhoni\tCSK\t12\t300
0          1\tVirat\tRCB\t12\t350
1  2\tFaf Du plesis\tRCB\t12\t625
2           3\tSurya\tMI\t12\t575
3       4\tYashashwi\tRR\t12\t600
4    5\tSanju Samson\tRR\t12\t425
5    6\tShubman Gill\tGT\t12\t610

In [90]:
df3 = pd.read_csv('players.csv',sep='\t', header=None, names=['Player','Team','Matches','Runs'] )
df3

Player Team  Matches  Runs
0       MS Dhoni  CSK       12   300
1          Virat  RCB       12   350
2  Faf Du plesis  RCB       12   625
3          Surya   MI       12   575
4      Yashashwi   RR       12   600
5   Sanju Samson   RR       12   425
6   Shubman Gill   GT       12   610

In [93]:
df4 = pd.read_csv('players.csv',sep='\t', header=None, names=['Player','Team','Matches','Runs','Age'] )
df4

Player Team  Matches  Runs  Age
0       MS Dhoni  CSK       12   300  NaN
1          Virat  RCB       12   350  NaN
2  Faf Du plesis  RCB       12   625  NaN
3          Surya   MI       12   575  NaN
4      Yashashwi   RR       12   600  NaN
5   Sanju Samson   RR       12   425  NaN
6   Shubman Gill   GT       12   610  NaN

In [97]:
df5 = pd.read_csv('players.csv',sep='\t', header=None, names=['Player','Team','Matches','Runs'] )
df5

Player Team  Matches  Runs
0       MS Dhoni  CSK       12   300
1          Virat  RCB       12   350
2  Faf Du plesis  RCB       12   625
3          Surya   MI       12   575
4      Yashashwi   RR       12   600
5   Sanju Samson   RR       12   425
6   Shubman Gill   GT       12   610

In [101]:
df6 = pd.read_csv('players.csv',sep='\t', header=None, names=['Player','Team','Matches','Runs'],na_values=['RCB'])

TypeError: read_csv() got an unexpected keyword argument 'sheet_name'

In [99]:
df6

Player Team  Matches  Runs
0       MS Dhoni  CSK       12   300
1          Virat  NaN       12   350
2  Faf Du plesis  NaN       12   625
3          Surya   MI       12   575
4      Yashashwi   RR       12   600
5   Sanju Samson   RR       12   425
6   Shubman Gill   GT       12   610

In [100]:
pwd()

'C:\\Data Science_Final\\Matplotlib'

In [102]:
df

Player_Name IPL_Team  Matches_Played  Runs_Scored
0       MS Dhoni      CSK              12          300
1          Virat      RCB              12          350
2  Faf Du plesis      RCB              12          625
3          Surya       MI              12          575
4      Yashashwi       RR              12          600
5   Sanju Samson       RR              12          425
6   Shubman Gill       GT              12          610

In [108]:
df['IPL_Team']

0    CSK
1    RCB
2    RCB
3     MI
4     RR
5     RR
6     GT
Name: IPL_Team, dtype: object

In [122]:
df.loc[[2,5],['Player_Name','Runs_Scored']]

Player_Name  Runs_Scored
2  Faf Du plesis          625
5   Sanju Samson          425

In [111]:
type(df.loc[2])

pandas.core.series.Series

In [116]:
df.loc[2:5,'Player_Name']

2    Faf Du plesis
3            Surya
4        Yashashwi
5     Sanju Samson
Name: Player_Name, dtype: object

In [119]:
df.iloc[2, 2:]

Matches_Played     12
Runs_Scored       625
Name: 2, dtype: object

In [120]:
df.iloc[6,[0,3]]

Player_Name    Shubman Gill
Runs_Scored             610
Name: 6, dtype: object

In [134]:
df7 = pd.read_csv('players.csv', sep='\t',header=None, nrows=2)
df7

0    1   2    3
0  MS Dhoni  CSK  12  300
1     Virat  RCB  12  350

In [138]:
df8=pd.date_range('17-05-2023',periods=7,freq='M')

C:\Users\lenovo\AppData\Local\Temp/ipykernel_29776/2393183384.py:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  df8=pd.date_range('17-05-2023',periods=7,freq='M')


In [139]:
type(df8)

pandas.core.indexes.datetimes.DatetimeIndex

In [141]:
import numpy as np
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [142]:
np.arange(7.0)

array([0., 1., 2., 3., 4., 5., 6.])

In [145]:
for i in range(7):
    print(i)

0
1
2
3
4
5
6


In [146]:
for i in np.arange(7):
    print(i)

0
1
2
3
4
5
6


In [148]:
pd.Series(range(5))

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [152]:
pd.Series(np.arange(5,10))

0    5
1    6
2    7
3    8
4    9
dtype: int32

In [157]:
index=['1st','2nd','3rd','4th','5th','Sumit']


In [158]:
pd.Series(np.arange(6), index=index)

1st      0
2nd      1
3rd      2
4th      3
5th      4
Sumit    5
dtype: int32

In [162]:
import csv

with open('players.csv') as f:
    lines = csv.reader(f)
    for i in lines:
        print(i)

['MS Dhoni\tCSK\t12\t300']
['Virat\tRCB\t12\t350']
['Faf Du plesis\tRCB\t12\t625']
['Surya\tMI\t12\t575']
['Yashashwi\tRR\t12\t600']
['Sanju Samson\tRR\t12\t425']
['Shubman Gill\tGT\t12\t610']


In [167]:
a=[1,2]
b=[3,4]

c=zip(a,b)
for i in c:
    print(i)

(1, 3)
(2, 4)


In [166]:
list(c)

[(1, 3), (2, 4)]

In [168]:
lines = [[a, b, c], [1, 2, 3], [4, 5, 6]]

In [169]:
list(zip(lines[1],lines[2]))

[(1, 4), (2, 5), (3, 6)]

In [170]:
k, v = lines[0], lines[1:]

In [171]:
k

[[1, 2], [3, 4], <zip at 0x2b01f2224c0>]

In [172]:
v

[[1, 2, 3], [4, 5, 6]]

In [175]:
from numpy.random import randn as rn

In [176]:
np.random.seed(100)

In [177]:
rn(5,4)

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604],
       [ 0.98132079,  0.51421884,  0.22117967, -1.07004333],
       [-0.18949583,  0.25500144, -0.45802699,  0.43516349],
       [-0.58359505,  0.81684707,  0.67272081, -0.10441114],
       [-0.53128038,  1.02973269, -0.43813562, -1.11831825]])

In [178]:
rn(5,4)

array([[ 1.61898166,  1.54160517, -0.25187914, -0.84243574],
       [ 0.18451869,  0.9370822 ,  0.73100034,  1.36155613],
       [-0.32623806,  0.05567601,  0.22239961, -1.443217  ],
       [-0.75635231,  0.81645401,  0.75044476, -0.45594693],
       [ 1.18962227, -1.69061683, -1.35639905, -1.23243451]])

In [191]:
np.random.seed(100)
np.random.random(5)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [187]:
import numpy as np

np.random.seed(42)  # Set the seed to a specific value

# Generate random numbers
random_numbers = np.random.random(5)
print(random_numbers)


[0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]


In [192]:
df

Player_Name IPL_Team  Matches_Played  Runs_Scored
0       MS Dhoni      CSK              12          300
1          Virat      RCB              12          350
2  Faf Du plesis      RCB              12          625
3          Surya       MI              12          575
4      Yashashwi       RR              12          600
5   Sanju Samson       RR              12          425
6   Shubman Gill       GT              12          610

In [200]:
print(df.loc[1].iloc[0])
print(df.loc[1].iloc[1])
print(df.loc[1].iloc[2])


Virat
RCB
12


In [202]:
df[df['Runs_Scored']>=575]

Player_Name IPL_Team  Matches_Played  Runs_Scored
2  Faf Du plesis      RCB              12          625
3          Surya       MI              12          575
4      Yashashwi       RR              12          600
6   Shubman Gill       GT              12          610

In [204]:
df['Age'] = [30,32,35,41,29,22,31]

In [205]:
df

Player_Name IPL_Team  Matches_Played  Runs_Scored  Age
0       MS Dhoni      CSK              12          300   30
1          Virat      RCB              12          350   32
2  Faf Du plesis      RCB              12          625   35
3          Surya       MI              12          575   41
4      Yashashwi       RR              12          600   29
5   Sanju Samson       RR              12          425   22
6   Shubman Gill       GT              12          610   31

In [210]:
df[(df['Runs_Scored']>575) & (df['Age']<30)]

Player_Name IPL_Team  Matches_Played  Runs_Scored  Age
4   Yashashwi       RR              12          600   29

In [217]:
df[(df['Runs_Scored']>575) & (df['Age']<30)].iloc[0,0]

'Yashashwi'

In [218]:
df[(df['Runs_Scored']>575) & (df['Age']<30)].loc[:,'Player_Name']

4    Yashashwi
Name: Player_Name, dtype: object

In [219]:
df[(df['Runs_Scored']>575) & (df['Age']<30)]['Player_Name']

4    Yashashwi
Name: Player_Name, dtype: object

In [223]:
d = {'name': ['s', 's', 's', 'k', 'k', 'k', 'l'],
    'income': [10, 20, 30, 40, 50, 60, 70],
    'comp': ['r','r','v','k','I','u','v']
    }

In [225]:
df9 = pd.DataFrame(d)
df9

name  income comp
0    s      10    r
1    s      20    r
2    s      30    v
3    k      40    k
4    k      50    I
5    k      60    u
6    l      70    v

In [228]:
df9.groupby('name').describe()

income                                          
      count  mean   std   min   25%   50%   75%   max
name                                                 
k       3.0  50.0  10.0  40.0  45.0  50.0  55.0  60.0
l       1.0  70.0   NaN  70.0  70.0  70.0  70.0  70.0
s       3.0  20.0  10.0  10.0  15.0  20.0  25.0  30.0

In [233]:
df11 = pd.DataFrame({'A': [10, 12, 13, 11, 10],
              'B': [19, 10, 15, 17, 18],
              'C': [13, 17, 18, 10, 11]}, index=['a','b','c','d','e'])
df11

A   B   C
a  10  19  13
b  12  10  17
c  13  15  18
d  11  17  10
e  10  18  11

In [234]:
df12 = pd.DataFrame({'A': [10, 12, 13, 11, 10],
              'B': [19, 10, 15, 17, 18],
              'C': [13, 17, 18, 10, 11]}, index=['f','g','h','i','j'])
df12

A   B   C
f  10  19  13
g  12  10  17
h  13  15  18
i  11  17  10
j  10  18  11

In [235]:
df13 = pd.DataFrame({'A': [10, 12, 13, 11, 10],
              'B': [19, 10, 15, 17, 18],
              'C': [13, 17, 18, 10, 11]}, index=['k','l','m','n','o'])
df13

A   B   C
k  10  19  13
l  12  10  17
m  13  15  18
n  11  17  10
o  10  18  11

In [236]:
pd.concat( [df11, df12, df13], axis=0)

A   B   C
a  10  19  13
b  12  10  17
c  13  15  18
d  11  17  10
e  10  18  11
f  10  19  13
g  12  10  17
h  13  15  18
i  11  17  10
j  10  18  11
k  10  19  13
l  12  10  17
m  13  15  18
n  11  17  10
o  10  18  11

In [237]:
pd.concat( [df11, df12, df13], axis=1)

A     B     C     A     B     C     A     B     C
a  10.0  19.0  13.0   NaN   NaN   NaN   NaN   NaN   NaN
b  12.0  10.0  17.0   NaN   NaN   NaN   NaN   NaN   NaN
c  13.0  15.0  18.0   NaN   NaN   NaN   NaN   NaN   NaN
d  11.0  17.0  10.0   NaN   NaN   NaN   NaN   NaN   NaN
e  10.0  18.0  11.0   NaN   NaN   NaN   NaN   NaN   NaN
f   NaN   NaN   NaN  10.0  19.0  13.0   NaN   NaN   NaN
g   NaN   NaN   NaN  12.0  10.0  17.0   NaN   NaN   NaN
h   NaN   NaN   NaN  13.0  15.0  18.0   NaN   NaN   NaN
i   NaN   NaN   NaN  11.0  17.0  10.0   NaN   NaN   NaN
j   NaN   NaN   NaN  10.0  18.0  11.0   NaN   NaN   NaN
k   NaN   NaN   NaN   NaN   NaN   NaN  10.0  19.0  13.0
l   NaN   NaN   NaN   NaN   NaN   NaN  12.0  10.0  17.0
m   NaN   NaN   NaN   NaN   NaN   NaN  13.0  15.0  18.0
n   NaN   NaN   NaN   NaN   NaN   NaN  11.0  17.0  10.0
o   NaN   NaN   NaN   NaN   NaN   NaN  10.0  18.0  11.0